/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIClass */

#ifndef _Included_JNIClass
#define _Included_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIClass
 * Method:    jniMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIClass_jniMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
